plugins {
    id 'com.android.application'
}

def runNo = (System.getenv("GITHUB_RUN_NUMBER") ?: "1").toInteger()

android {
    namespace 'cloud.neonnews.prompter'
    compileSdk 34

    defaultConfig {
        applicationId 'cloud.neonnews.prompter'
        minSdk 24
        targetSdk 34
        versionCode runNo
        versionName "1.0." + runNo
    }

    signingConfigs {
        release {
            storeFile file('neon.keystore')
            storePassword 'neonprompter'
            keyAlias 'neon'
            keyPassword 'neonprompter'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    androidResources {
        noCompress 'zip'
    }
}

dependencies {
    implementation 'net.java.dev.jna:jna:5.13.0@aar'
    implementation 'com.alphacephei:vosk-android:0.3.47@aar'
}
